const fs = require('fs');
const path = require('path');
const express = require('express');
const db = require('../db');
const { requireAuth, mayEdit } = require('../middleware/auth');
const { encode } = require('../../bot/clipManager');
const router = express.Router();
router.use(requireAuth);
function hasGuild(req, guildId) { return req.user.guildIds?.includes(guildId); }
router.get('/', (req, res) => { const guild = req.query.guild; if (!guild || !hasGuild(req, guild)) return res.status(403).json({ error: 'Guild access denied.' }); const limit = Math.min(Number(req.query.limit) || 10, 50), offset = Number(req.query.offset) || 0; const rows = db.prepare('SELECT id, duration, users_involved, created_at, favorited, created_by FROM clips WHERE guild_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?').all(guild, limit, offset); res.json(rows.map(r => ({ ...r, users: JSON.parse(r.users_involved), favorited: Boolean(r.favorited) }))); });
router.get('/:id/metadata', (req, res) => { const clip = db.prepare('SELECT * FROM clips WHERE id=?').get(req.params.id); if (!clip || !hasGuild(req, clip.guild_id)) return res.status(404).json({ error: 'Clip not found.' }); res.json({ ...clip, users_involved: JSON.parse(clip.users_involved), user_mutes: JSON.parse(clip.user_mutes), user_volumes: JSON.parse(clip.user_volumes) }); });
router.get('/:id/audio', (req, res) => { const clip = db.prepare('SELECT * FROM clips WHERE id=?').get(req.params.id); if (!clip || !hasGuild(req, clip.guild_id)) return res.status(404).end(); res.sendFile(path.resolve(clip.edited_audio_path || path.join(clip.original_audio_path, 'original.mp3'))); });
router.get('/:id/preview', (req, res) => res.redirect(`/api/clips/${req.params.id}/audio`));
router.post('/:id/edit', async (req, res, next) => { try { const clip = db.prepare('SELECT * FROM clips WHERE id=?').get(req.params.id); if (!clip || !mayEdit(req, clip)) return res.status(403).json({ error: 'Only the creator or a server admin can edit.' }); const start = Math.max(0, Number(req.body.start_trim) || 0), end = Math.min(clip.duration, Number(req.body.end_trim) || clip.duration); if (end <= start) return res.status(400).json({ error: 'End trim must be after start trim.' }); const mutes = req.body.user_mutes || {}, volumes = req.body.user_volumes || {}; const users = JSON.parse(clip.users_involved).filter(u => !mutes[u.id]); if (!users.length) return res.status(400).json({ error: 'At least one user must remain unmuted.' }); const output = path.join(clip.original_audio_path, 'edited.mp3'); await encode(users.map(u => path.join(clip.original_audio_path, `${u.id}.pcm`)), output, { start, end, volumes: users.map(u => Math.min(2, Math.max(.5, Number(volumes[u.id]) || 1))) }); db.prepare('UPDATE clips SET edited_audio_path=?, start_trim=?, end_trim=?, user_mutes=?, user_volumes=? WHERE id=?').run(output, start, end, JSON.stringify(mutes), JSON.stringify(volumes), clip.id); res.json({ ok: true, audio_url: `/api/clips/${clip.id}/audio` }); } catch (error) { next(error); } });
router.post('/:id/favorite', (req, res) => { const clip = db.prepare('SELECT * FROM clips WHERE id=?').get(req.params.id); if (!clip || !mayEdit(req, clip)) return res.status(403).json({ error: 'Not allowed.' }); db.prepare('UPDATE clips SET favorited=? WHERE id=?').run(req.body.favorited ? 1 : 0, clip.id); res.json({ ok: true }); });
router.delete('/:id', (req, res) => { const clip = db.prepare('SELECT * FROM clips WHERE id=?').get(req.params.id); if (!clip || !mayEdit(req, clip)) return res.status(403).json({ error: 'Not allowed.' }); fs.rmSync(clip.original_audio_path, { recursive: true, force: true }); db.prepare('DELETE FROM clips WHERE id=?').run(clip.id); res.status(204).end(); });
module.exports = router;
