const path = require('path');
const express = require('express');
const session = require('express-session');
const SQLiteSessionStore = require('./sessionStore');
const { loadConfig, log } = require('../bot/utils');
const db = require('./db');
const config = loadConfig(), app = express();
app.use(express.json());
if (process.env.NODE_ENV === 'production' && !process.env.SESSION_SECRET) throw new Error('SESSION_SECRET must be set in production.');
app.set('trust proxy', 1);
const sessionStore = new SQLiteSessionStore(db);
sessionStore.cleanup();
app.use((req, res, next) => { res.setHeader('X-Content-Type-Options', 'nosniff'); res.setHeader('X-Frame-Options', 'DENY'); res.setHeader('Referrer-Policy', 'same-origin'); next(); });
app.use(session({ store: sessionStore, name: 'clipvault.sid', secret: process.env.SESSION_SECRET || 'development-only-secret', resave: false, saveUninitialized: false, cookie: { secure: process.env.NODE_ENV === 'production', httpOnly: true, sameSite: 'lax', maxAge: 7 * 86400000 } }));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/clips', require('./routes/clips'));
app.use('/api/settings', require('./routes/settings'));
app.use('/api/admins', require('./routes/admins'));
app.use('/api/discord', require('./routes/discord'));
app.get('/api/health', (req, res) => res.json({ ok: true, mode: process.env.NODE_ENV || 'development' }));
app.use(express.static(path.resolve(process.cwd(), 'web')));
app.use((error, req, res, next) => { log(error.stack || error.message); res.status(500).json({ error: 'Internal server error.' }); });
app.listen(config.api.port, config.api.host || '127.0.0.1', () => log(`Dashboard and API listening at ${config.api.baseUrl}`));
