let all = [], offset = 0, guild = new URLSearchParams(location.search).get('guild'), currentUser;
const clips = document.querySelector('#clips'), status = document.querySelector('#status'), more = document.querySelector('#more');
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]);
document.querySelector('#theme').onclick = () => { document.body.classList.toggle('light'); localStorage.theme = document.body.classList.contains('light') ? 'light' : 'dark'; }; if (localStorage.theme === 'light') document.body.classList.add('light');
document.querySelector('#logout').onclick = async () => { await fetch('/api/auth/logout', { method: 'POST' }); location.reload(); };
document.querySelector('#devLogin').onclick = async () => { const res = await fetch('/api/auth/dev', { method: 'POST' }); if (res.ok) location.reload(); else status.textContent = 'Local development login failed.'; };
function queryUrl() { return `?guild=${encodeURIComponent(guild)}`; }
function render() { const query = document.querySelector('#search').value.toLowerCase(); const filtered = all.filter(c => JSON.stringify(c).toLowerCase().includes(query)); document.querySelector('#count').textContent = `${all.length} clip${all.length === 1 ? '' : 's'}`; clips.innerHTML = filtered.map(c => `<article class="clip"><div><p class="eyebrow">${new Date(c.created_at).toLocaleDateString()}</p><h2>Clip ${escapeHtml(c.id)}</h2><div class="muted">${Math.round(c.duration)} seconds · ${c.users.map(u => escapeHtml(u.name)).join(', ')}</div></div><div class="actions"><a class="button" href="editor.html?clip_id=${encodeURIComponent(c.id)}">Edit</a><button data-id="${escapeHtml(c.id)}" class="fav quiet">${c.favorited ? '★ Favorited' : '☆ Favorite'}</button></div></article>`).join('') || '<div class="empty">No clips match this search.</div>'; document.querySelectorAll('.fav').forEach(button => button.onclick = async () => { await fetch(`/api/clips/${button.dataset.id}/favorite`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ favorited: !button.textContent.includes('★') }) }); load(true); }); }
async function load(reset = false) { if (reset) { all = []; offset = 0; } const res = await fetch(`/api/clips?guild=${encodeURIComponent(guild)}&limit=10&offset=${offset}`); if (!res.ok) { status.textContent = 'Unable to load clips for this server.'; return; } const data = await res.json(); all.push(...data); offset += data.length; more.hidden = data.length < 10; render(); }
async function init() { const [meResponse, modeResponse] = await Promise.all([fetch('/api/auth/me'), fetch('/api/auth/mode')]); currentUser = await meResponse.json(); const mode = await modeResponse.json(); if (!currentUser) { document.querySelector('#devLogin').hidden = !mode.developmentLogin; return; } document.querySelector('#login').hidden = true; document.querySelector('#devLogin').hidden = true; document.querySelector('#logout').hidden = false; const picker = document.querySelector('#guild'); const guilds = currentUser.guilds || []; if (!guild && guilds.length) guild = guilds[0].id; if (!guild) return status.textContent = 'Your Discord account is not in any servers.'; picker.innerHTML = guilds.map(item => `<option value="${escapeHtml(item.id)}" ${item.id === guild ? 'selected' : ''}>${escapeHtml(item.name)}</option>`).join(''); picker.onchange = () => { guild = picker.value; location.search = queryUrl(); }; document.querySelector('#guildPicker').hidden = false; document.querySelector('#clipPanel').hidden = false; document.querySelector('#adminLink').href = `admin.html${queryUrl()}`; const canManage = currentUser.accessGuilds?.includes(guild); document.querySelector('#adminLink').hidden = !canManage; status.textContent = `${currentUser.development ? 'Development mode · ' : ''}Signed in as ${currentUser.username}`; document.querySelector('#search').oninput = render; more.onclick = () => load(); load(); }
init();
